spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://mysql:3306/samozanet
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    initialize: true
    initialization-mode: always
    sql-script-encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  freemarker:
    expose-request-attributes: true
