version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: samozanet
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "6033:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  app:
    build: ./
    container_name: java-app
    restart: always
    depends_on:
      - mysql
    ports:
      - 8080:8080