version: '3.8'

services:
#  mysql:
#    container_name: mysql
#    image: mysql
#    restart: always
#    environment:
#      MYSQL_DATABASE: samozanet
#      MYSQL_ROOT_HOST: '%'
#      MYSQL_USERNAME: vint
#      MYSQL_PASSWORD: ~Q+~%o3Zj+o}R*H4+X-aVKb+
#      MYSQL_ROOT_PASSWORD: ~Q+~%o3Zj+o}R*H4+X-aVKb+
#    ports:
#      - "6033:3306"
#    volumes:
#      - ./sql:/docker-entrypoint-initdb.d

  app:
    build: ./
    container_name: samozanet
    ports:
      - 8080:8080
    network_mode: "host"